name: signac
channels:
 - bioconda
 - conda-forge
 - anaconda
dependencies:
 - python>=3.7
 - snakemake
 - macs2
 - r-base=4.0.3
 - hdf5
 - htslib
 - leidenalg
 - python-igraph
 - pip
 - pip:
   - umap-learn
   - scale-atac
   - scanpy
